# # # # # # # # # # # # # # # # # # # # # # # # # #
#    █████████            ███                     #   ████████
#   ███░░░░░███          ░░░                      #  ███░░░░███
#  ███     ░░░   ██████  ████  ████████    █████  # ░░░    ░███
# ░███          ███░░███░░███░ ░███░░███  ███░░   #    ███████
# ░███         ░███ ░███ ░███  ░███ ░███░ ░█████  #   ███░░░░
# ░░███     ███░███ ░███ ░███  ░███ ░███  ░░░░███ #  ███      █
#  ░░█████████ ░░██████  █████ ████ █████ ██████  # ░██████████
#   ░░░░░░░░░   ░░░░░░  ░░░░░░ ░░░ ░░░░░░ ░░░░░   # ░░░░░░░░░░
# # # # # # # # # # # # # # # # # # # # # # # # # #
# https://manytools.org/hacker-tools/ascii-banner/ // DOS Rebel // Wide

# The main language used in-game.
# Included: English, Dutch, German, French, Spanish, Swedish, Chinese, Italian, Hungarian
language: English

# Naming of the currency and coins.
naming:
  symbol: $       # currency symbol
  single: Coin    # single name of a coin item
  plural: Coins   # plural name of a coin item
  color: ffaa00   # the color of the display name

# Define any kind of coin that you ever dreamt of.
# Check out: https://github.com/JustEli/Coins/wiki/defining-coins
coins:
  Block:
    item: gold block
    worth: [10.0, 15.0]
    glow: true
  Ingot:
    item: gold ingot
    worth: [5.0, 9.0]
  Nugget:
    item: gold nugget
    worth: [1.0, 4.0]
    stack: true

# The way currency and action bars are shown.
# Check out: https://github.com/JustEli/Coins/wiki/display-settings
display:
  currency: "${naming.currency}${_amount}"
  deposit: "&2+ &a${display.currency}"
  withdraw: "&4- &c${display.currency}"

# Tell the plugin when and what coins to drop.
# Check out: https://github.com/JustEli/Coins/wiki/defining-drops
drops:
  playerKill:
    enabled: false
    handling:
      instances: [Player]
      events: [KILL_ENTITY]
      entities: []
    preventAlts: true
    chance:
      Block: 0.1
      Ingot: 0.2
      Nugget: 0.4
  hostileKill:
    enabled: true
    spawners: false
    splitReward: false
    instances: [Monster, Boss, Flying, Slime, Wolf]
    events: [KILL_ENTITY]
    entities: []
  passiveKill:
    enabled: false
    spawners: false
    instance: [Mob]
    events: [KILL_ENTITY]
    entities: []
  entityDeath:
    enabled: false
    handling:
      events: [ENTITY_DEATH]
  mineBlock:
    enabled: true
    materials: []
    events: [BREAK_BLOCK]
  catchFish:
    enabled: false
    events: [CATCH_FISH]
  unlockRecipe:
    enabled: false
    events: [UNLOCK_RECIPE]
  achievement:
    enabled: false
    events: [ACHIEVEMENT_GET]
  tamePet:
    enabled: false
    events: [TAME_PET]
  breedAnimal:
    enabled: false
    events: [BREED_ANIMAL]
  repairItem:
    enabled: false
    events: [REPAIR_ITEM]
  enchantItem:
    enabled: false
    events: [ENCHANT_ITEM]
  brewPotion:
    enabled: false
    events: [BREW_POTION]

settings:
  coinDecimals: 2
  percentagePlayerHit: 0.9
  disableHoppers: false
  soundVolume: 0.5
  limitForLocation: 1
  disabledWorlds: []

withdraw:
  enabled: true
  values:
    Block: [1000.01, 10000.0]
    Ingot: [100.01, 1000.0]
    Nugget: [1.0, 100.0]
  deposit: [LEFT_CLICK, RIGHT_CLICK, PICKUP] #CONTAINER, COMMAND

death:
  enabled: true
  takePercentage: false
  takeAmount: [10, 30] # instead can allow [10%, 30%]
  preventNegativeBalance: true
  dropAtDeathLocation: false

economy:
  integration: false
  effects: true
  startingBalance: 100
  track: false
  maximumBalance: 1000000000000